item {
  id: 1
  name: 'Ace'
}

item {
  id: 2
  name: 'Two'
}

item {
  id: 3
  name: 'Three'
}

item {
  id: 4
  name: 'Four'
}

item {
  id: 5
  name: 'Five'
}

item {
  id: 6
  name: 'Six'
}

item {
  id: 7
  name: 'Seven'
}

item {
  id: 8
  name: 'Fante'
}

item {
  id: 9
  name: 'Caval'
}

item {
  id: 10
  name: 'Re'
}